language: r
warnings_are_errors: false
r:
  - oldrel
  - release
os:
  - linux
  - osx
osx_image: # using null for the default value
  - null
  # macOS 10.14 / xcode10.2 is particularly troublesome
  - xcode10.2
